# average cpu usage of all cores
float32 cpu_usage
# network usage for all nics
float32 mega_bit_upload
float32 mega_bit_download
# overall packet loss
float32 packet_loss_percent
# packets sent since last reading
uint32 packets_sent
# packets received since last reading
uint32 packets_received
# packets sent dropped/error since last reading
uint32 packets_sent_dropped
# packets received dropped/error since last reading
uint32 packets_received_dropped